//#######################################################################
//File generated by BMP2C V1.18 17.01.2008
//hk@holger-klabunde.de
//http://www.holger-klabunde.de
//6 pixel per byte for T6963 and 6x8 font
//Horizontal pixel orientation for T6963
//Pixel orientation per Byte: D7..D0 
//#######################################################################
#ifndef Clear_sky_n_h //don't do multiple includes of this file
#define Clear_sky_n_h

#include <pgmspace.h> //Win-AVR
//#include <progmem.h> //AVR-GCC

#define Clear_sky_nWIDTH 	22	//Width in pixels
#define Clear_sky_nHEIGHT 	22	//Height in pixels
#define Clear_sky_nBYTEWIDTH 	4	//Width in bytes

//extern const rom unsigned char Clear_sky_nbmp[]; //Microchip C18
//extern const unsigned char code Clear_sky_nbmp[]; //Keil
//extern const unsigned char Clear_sky_nbmp[]; //SDCC

extern extern const char Clear_sky_nbmp[]; //AVR-GCC, WinAVR

#endif //Clear_sky_n_h
