//#######################################################################
//File generated by BMP2C V1.18 17.01.2008
//hk@holger-klabunde.de
//http://www.holger-klabunde.de
//6 pixel per byte for T6963 and 6x8 font
//Horizontal pixel orientation for T6963
//Pixel orientation per Byte: D7..D0 
//#######################################################################
#ifndef Fair_n_h //don't do multiple includes of this file
#define Fair_n_h

#include <pgmspace.h> //Win-AVR
//#include <progmem.h> //AVR-GCC

#define Fair_nWIDTH 	22	//Width in pixels
#define Fair_nHEIGHT 	22	//Height in pixels
#define Fair_nBYTEWIDTH 	4	//Width in bytes

//extern const rom unsigned char Fair_nbmp[]; //Microchip C18
//extern const unsigned char code Fair_nbmp[]; //Keil
//extern const unsigned char Fair_nbmp[]; //SDCC

extern extern const char Fair_nbmp[]; //AVR-GCC, WinAVR

#endif //Fair_n_h
