//#######################################################################
//File generated by BMP2C V1.18 17.01.2008
//hk@holger-klabunde.de
//http://www.holger-klabunde.de
//6 pixel per byte for T6963 and 6x8 font
//Horizontal pixel orientation for T6963
//Pixel orientation per Byte: D7..D0 
//#######################################################################
#ifndef Partly_cloudy_n_h //don't do multiple includes of this file
#define Partly_cloudy_n_h

#include <pgmspace.h> //Win-AVR
//#include <progmem.h> //AVR-GCC

#define Partly_cloudy_nWIDTH 	22	//Width in pixels
#define Partly_cloudy_nHEIGHT 	22	//Height in pixels
#define Partly_cloudy_nBYTEWIDTH 	4	//Width in bytes

//extern const rom unsigned char Partly_cloudy_nbmp[]; //Microchip C18
//extern const unsigned char code Partly_cloudy_nbmp[]; //Keil
//extern const unsigned char Partly_cloudy_nbmp[]; //SDCC

extern extern const char Partly_cloudy_nbmp[]; //AVR-GCC, WinAVR

#endif //Partly_cloudy_n_h
