//#######################################################################
//File generated by BMP2C V1.18 17.01.2008
//hk@holger-klabunde.de
//http://www.holger-klabunde.de
//6 pixel per byte for T6963 and 6x8 font
//Horizontal pixel orientation for T6963
//Pixel orientation per Byte: D7..D0 
//#######################################################################
#ifndef Sleet_showers_and_thunder_n_h //don't do multiple includes of this file
#define Sleet_showers_and_thunder_n_h

#include <pgmspace.h> //Win-AVR
//#include <progmem.h> //AVR-GCC

#define Sleet_showers_and_thunder_nWIDTH 	22	//Width in pixels
#define Sleet_showers_and_thunder_nHEIGHT 	22	//Height in pixels
#define Sleet_showers_and_thunder_nBYTEWIDTH 	4	//Width in bytes

//extern const rom unsigned char Sleet_showers_and_thunder_nbmp[]; //Microchip C18
//extern const unsigned char code Sleet_showers_and_thunder_nbmp[]; //Keil
//extern const unsigned char Sleet_showers_and_thunder_nbmp[]; //SDCC

extern extern const char Sleet_showers_and_thunder_nbmp[]; //AVR-GCC, WinAVR

#endif //Sleet_showers_and_thunder_n_h
